---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        envFrom: []
        env:
        - name: EXTERNAL_DNS_PIHOLE_SERVER
          value: "https://pihole.local.zachary.day"
        - name: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
          value: "false"
        - name: EXTERNAL_DNS_PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-credentials
              key: password
        args:
        - --source=service
        - --source=ingress
        - --source=gateway-httproute
        - --source=gateway-grpcroute
        - --registry=noop
        - --policy=upsert-only
        - --provider=pihole
        - --pihole-api-version=6
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
